version: 0.2

phases:
  install:
    runtime-versions:
      docker: latest
    commands:
      - apt-get update -y && apt-get install -y awscli
      - aws --version
      - docker --version

  pre_build:
    commands:
      - echo "Iniciando CodeBuild"
      - terraform --version
      - aws --version
      - terraform init
      - echo "Iniciando login a ECR"
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=$(aws ecr describe-repositories --repository-names "grpc-app" --query 'repositories[0].repositoryUri' --output text)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo "Construyendo imágenes Docker"
      - cd servidor
      - docker build -t $REPOSITORY_URI:servidor-$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:servidor-$IMAGE_TAG $REPOSITORY_URI:servidor-latest
      - cd ../cliente
      - docker build -t $REPOSITORY_URI:cliente-$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:cliente-$IMAGE_TAG $REPOSITORY_URI:cliente-latest
      - cd ..
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Subiendo imágenes a ECR"
      - docker push $REPOSITORY_URI:servidor-$IMAGE_TAG
      - docker push $REPOSITORY_URI:servidor-latest
      - docker push $REPOSITORY_URI:cliente-$IMAGE_TAG
      - docker push $REPOSITORY_URI:cliente-latest
      - echo "Aplicando cambios de Terraform"
      - terraform apply -auto-approve tfplan
      - echo "Build completado"